Repository Polly-Contrib/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock, pull requests merged in 2020-02, with the labels that each got.

#1 Add template
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  GitVersionConfig.yaml
  LICENSE
  LICENSE.txt
  README.md
  build.bat
  build.cake
  build.ps1
  build.sh
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.Specs/MyContribSpecs.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.Specs/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.Specs.csproj
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.sln
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.snk
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/MyContrib.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.csproj
Labels: documentation

#2 Add redis distributed lock
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.Specs/DistributedLockTests.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.Specs/MyContribSpecs.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.Specs/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.Specs.csproj
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.sln
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/IRedisConnection.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/MyContrib.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock.csproj
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/RedisConnection.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/RedisDistributedLockProvider.cs
  src/Polly.Contrib.DuplicateRequestCollapser.RedisDistributedLock/RedisDistributedLockProviderOptions.cs
  src/Readme.md
Labels: feature

#3 Add AppVeyor build; Ensure AppVeyor branch-build numbers are unique
  appveyor.yml
  build.cake
Labels: CI/build
